wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.12
    cli_version: 0.18.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1773645374
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.7.12
      5: 0.18.7
      8:
      - 5
      13: linux-x86_64
mut_rate_int:
  desc: null
  value: 14
potts_df:
  desc: null
  value: 20
potts_lambda_J:
  desc: null
  value: 3.947717136629693
potts_p_edge:
  desc: null
  value: 0.8989479053986831
potts_p_rescue:
  desc: null
  value: 0.037597073261493606
seed:
  desc: null
  value: 1
seq_length:
  desc: null
  value: 25
seq:
  desc: null
  value: AAAAAAACCCCCAAAAAAUCGGCUG
seq_length_actual:
  desc: null
  value: 25
mut_rate:
  desc: null
  value: 0.56
