"""Plot the ResidualBind VTS1 scatter-by-mutation-count figure.

This script is intentionally plotting-only. It consumes the reusable
`scatter_by_mutcount_predictions.npz` artifact generated by
`mRNA_RBP/scripts/pipeline/generate_residualbind_vts1_scatter_predictions.py`.
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import numpy as np


REPO = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(REPO))
from mRNA_RBP.scripts.figures.core.provenance import stamp_figure  # noqa: E402


COLLECTION_DIR = (
    REPO
    / "mRNA_RBP"
    / "outputs"
    / "ground_truth_collections"
    / "ResidualBind oracle VTS1"
)
LIB_DIR = COLLECTION_DIR / "libraries_used_for_figures"
FIG_DIR = COLLECTION_DIR / "figures"
PREDICTIONS_PATH = LIB_DIR / "scatter_by_mutcount_predictions.npz"
MUT_RATES = (5, 10, 25)

COLOR_RAND = "#4C9BE8"
SCATTER_S = 2
ALPHA_RAND = 0.15
ALPHA_EVAL = 0.35


def _mut_count_colors(unique_counts):
    cmap = cm.get_cmap("plasma_r", len(unique_counts) + 2)
    return {m: cmap(i + 1) for i, m in enumerate(sorted(unique_counts))}


def _scalar(z, key):
    return float(np.asarray(z[key], dtype=float))


def load_panel_data(path: Path):
    if not path.exists():
        raise FileNotFoundError(
            f"Missing scatter prediction artifact: {path}\n"
            "Generate it once with:\n"
            "  python mRNA_RBP/scripts/pipeline/generate_residualbind_vts1_scatter_predictions.py"
        )
    z = np.load(path)
    panel_data = []
    for pct in MUT_RATES:
        panel_data.append(
            {
                "y_rand": z[f"y_rand_{pct}"].astype(float),
                "yhat_rand": z[f"yhat_rand_{pct}"].astype(float),
                "y_activity": z[f"y_activity_{pct}"].astype(float),
                "yhat_activity": z[f"yhat_activity_{pct}"].astype(float),
                "rate_labels": z[f"rate_labels_{pct}"].astype(int),
                "rho_rand": _scalar(z, f"rho_rand_{pct}"),
                "rho_activity": _scalar(z, f"rho_activity_{pct}"),
                "r2_rand": _scalar(z, f"r2_rand_{pct}"),
                "r2_activity": _scalar(z, f"r2_activity_{pct}"),
                "rmse_rand": _scalar(z, f"rmse_rand_{pct}"),
                "rmse_activity": _scalar(z, f"rmse_activity_{pct}"),
            }
        )
    return panel_data


def main() -> int:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    panel_data = load_panel_data(PREDICTIONS_PATH)

    all_gt = np.concatenate([d["y_rand"] for d in panel_data] + [d["y_activity"] for d in panel_data])
    all_yh = np.concatenate([d["yhat_rand"] for d in panel_data] + [d["yhat_activity"] for d in panel_data])
    lo = float(np.nanpercentile(np.concatenate([all_gt, all_yh]), 0.2))
    hi = float(np.nanpercentile(np.concatenate([all_gt, all_yh]), 99.8))
    pad = (hi - lo) * 0.04
    lim = [lo - pad, hi + pad]

    all_counts = sorted(set(np.concatenate([d["rate_labels"] for d in panel_data])))
    colors = _mut_count_colors(all_counts)

    fig, axes = plt.subplots(1, 3, figsize=(18, 6))
    fig.subplots_adjust(wspace=0.3)

    for ax, pct, data in zip(axes, MUT_RATES, panel_data):
        ax.scatter(
            data["y_rand"],
            data["yhat_rand"],
            s=SCATTER_S,
            alpha=ALPHA_RAND,
            color=COLOR_RAND,
            rasterized=True,
            label="random holdout",
        )
        for m in all_counts:
            mask = data["rate_labels"] == m
            if mask.any():
                ax.scatter(
                    data["y_activity"][mask],
                    data["yhat_activity"][mask],
                    s=SCATTER_S,
                    alpha=ALPHA_EVAL,
                    color=colors[m],
                    rasterized=True,
                    label=f"{m}-mut (n={mask.sum():,})",
                )

        ax.plot(lim, lim, "k--", linewidth=0.9)
        ax.set_xlim(lim)
        ax.set_ylim(lim)
        ax.set_xlabel("y (ResidualBind VTS1 score)", fontsize=10)
        if ax is axes[0]:
            ax.set_ylabel("yhat (surrogate)", fontsize=10)
        ax.set_title(f"{pct}% mut rate  (lib=20,000)", fontsize=10)
        stats_txt = (
            f"random holdout: rho={data['rho_rand']:.3f}  R2={data['r2_rand']:.3f}  RMSE={data['rmse_rand']:.3f}\n"
            f"activity-balanced: rho={data['rho_activity']:.3f}  R2={data['r2_activity']:.3f}  RMSE={data['rmse_activity']:.3f}"
        )
        ax.text(
            0.97,
            0.97,
            stats_txt,
            transform=ax.transAxes,
            fontsize=9,
            va="top",
            ha="right",
            bbox=dict(boxstyle="round,pad=0.4", fc="white", alpha=0.85),
        )
        handles, labels = ax.get_legend_handles_labels()
        leg = ax.legend(handles, labels, markerscale=5, fontsize=8, framealpha=0.85, loc="lower right")
        legend_handles = getattr(leg, "legend_handles", None)
        if legend_handles is None:
            legend_handles = getattr(leg, "legendHandles", [])
        for h in legend_handles:
            h.set_alpha(1.0)

    mutrate_dir = FIG_DIR / "mutation_rate_sweep"
    mutrate_dir.mkdir(parents=True, exist_ok=True)
    out = mutrate_dir / "scatter_by_mutcount.png"
    stamp_figure(
        fig,
        library_status="fresh",
        source_paths=[PREDICTIONS_PATH]
        + [
            LIB_DIR / "random_libraries" / f"mut{pct:02d}_lib_20000.npz"
            for pct in MUT_RATES
        ]
        + [LIB_DIR / "activity_balanced.npz"],
    )
    fig.savefig(out, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
