wandb_version: 1

mut_rate_int:
  value: 10
potts_df:
  value: 5
potts_lambda_J:
  value: 1.9044721990914928
potts_p_edge:
  value: 0.4137164158956969
potts_p_rescue:
  value: 0.2781863988526786
seed:
  value: 2
seq_length:
  value: 60
