wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 2
potts_lambda_J:
  value: 0.5448490396026774
potts_p_edge:
  value: 0.8092136109110117
potts_p_rescue:
  value: 0.06134888239430165
seed:
  value: 0
seq_length:
  value: 25
