wandb_version: 1

mut_rate_int:
  value: 2
potts_df:
  value: 5
potts_lambda_J:
  value: 3.9246598671613855
potts_p_edge:
  value: 0.9229824363230388
potts_p_rescue:
  value: 0.19287531719192733
seed:
  value: 1
seq_length:
  value: 80
