wandb_version: 1

mut_rate_int:
  value: 4
potts_df:
  value: 2
potts_lambda_J:
  value: 4.045273420175283
potts_p_edge:
  value: 0.35785475572164993
potts_p_rescue:
  value: 0.12844815951248803
seed:
  value: 2
seq_length:
  value: 35
