wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 2.5544145343216176
potts_p_edge:
  value: 0.9448623914728024
potts_p_rescue:
  value: 0.1759938948320473
seed:
  value: 1
seq_length:
  value: 60
