wandb_version: 1

mut_rate_int:
  value: 4
potts_df:
  value: 20
potts_lambda_J:
  value: 2.648775015282768
potts_p_edge:
  value: 0.5155655877810597
potts_p_rescue:
  value: 0.22779259209359976
seed:
  value: 2
seq_length:
  value: 20
