wandb_version: 1

mut_rate_int:
  value: 4
potts_df:
  value: 5
potts_lambda_J:
  value: 3.250384924086574
potts_p_edge:
  value: 0.8556850178132771
potts_p_rescue:
  value: 0.016593000668088276
seed:
  value: 2
seq_length:
  value: 100
