wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 10
potts_lambda_J:
  value: 3.143036444266674
potts_p_edge:
  value: 0.7426536583228514
potts_p_rescue:
  value: 0.1189464089094662
seed:
  value: 2
seq_length:
  value: 25
