wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 3.6978263894437817
potts_p_edge:
  value: 0.8657437015986917
potts_p_rescue:
  value: 0.0976741614828016
seed:
  value: 2
seq_length:
  value: 15
