wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 1.101364463089185
potts_p_edge:
  value: 0.7531272321367185
potts_p_rescue:
  value: 0.13555128745309644
seed:
  value: 2
seq_length:
  value: 20
