wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 2.396441740960924
potts_p_edge:
  value: 0.8270644825317528
potts_p_rescue:
  value: 0.07104120238263383
seed:
  value: 1
seq_length:
  value: 20
