wandb_version: 1

mut_rate_int:
  value: 2
potts_df:
  value: 20
potts_lambda_J:
  value: 4.2093186951909365
potts_p_edge:
  value: 0.6186480785632429
potts_p_rescue:
  value: 0.1347564694662715
seed:
  value: 1
seq_length:
  value: 20
