wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 2
potts_lambda_J:
  value: 1.0258067615528803
potts_p_edge:
  value: 0.7670338035085029
potts_p_rescue:
  value: 0.17088069377375165
seed:
  value: 1
seq_length:
  value: 35
