wandb_version: 1

mut_rate_int:
  value: 2
potts_df:
  value: 2
potts_lambda_J:
  value: 4.008131268268862
potts_p_edge:
  value: 0.777422417857174
potts_p_rescue:
  value: 0.25290191043938515
seed:
  value: 0
seq_length:
  value: 100
