wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 3.652758920187788
potts_p_edge:
  value: 0.8765551572163559
potts_p_rescue:
  value: 0.06044525379405907
seed:
  value: 0
seq_length:
  value: 20
