wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 3.718029996207415
potts_p_edge:
  value: 0.8321194586668261
potts_p_rescue:
  value: 0.08030726516063874
seed:
  value: 0
seq_length:
  value: 15
