wandb_version: 1

mut_rate_int:
  value: 4
potts_df:
  value: 2
potts_lambda_J:
  value: 2.545258330549353
potts_p_edge:
  value: 0.8251371510220167
potts_p_rescue:
  value: 0.19848989299737943
seed:
  value: 2
seq_length:
  value: 80
