wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 2
potts_lambda_J:
  value: 3.9691489923036007
potts_p_edge:
  value: 0.6375684526431127
potts_p_rescue:
  value: 0.14603902628253493
seed:
  value: 2
seq_length:
  value: 15
