wandb_version: 1

mut_rate_int:
  value: 8
potts_df:
  value: 20
potts_lambda_J:
  value: 2.296745454994573
potts_p_edge:
  value: 0.5422276492553509
potts_p_rescue:
  value: 0.024681781173599957
seed:
  value: 2
seq_length:
  value: 20
