wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 2.846542558053263
potts_p_edge:
  value: 0.7779280789542258
potts_p_rescue:
  value: 0.10744504857970268
seed:
  value: 1
seq_length:
  value: 30
