wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.953255612809709
potts_p_edge:
  value: 0.8489077469183504
potts_p_rescue:
  value: 0.04141344108329874
seed:
  value: 2
seq_length:
  value: 15
