wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 10
potts_lambda_J:
  value: 4.5206088740945045
potts_p_edge:
  value: 0.9345121817770096
potts_p_rescue:
  value: 0.093454271834493
seed:
  value: 0
seq_length:
  value: 41
