wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 10
potts_lambda_J:
  value: 3.379311637818107
potts_p_edge:
  value: 0.811225694393533
potts_p_rescue:
  value: 0.005419979210479431
seed:
  value: 1
seq_length:
  value: 15
