wandb_version: 1

mut_rate_int:
  value: 4
potts_df:
  value: 2
potts_lambda_J:
  value: 3.840731730268229
potts_p_edge:
  value: 0.44108064787785384
potts_p_rescue:
  value: 0.1201597111668228
seed:
  value: 1
seq_length:
  value: 80
