wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.833536707993987
potts_p_edge:
  value: 0.6962107142169739
potts_p_rescue:
  value: 0.04094751656863383
seed:
  value: 0
seq_length:
  value: 15
