wandb_version: 1

mut_rate_int:
  value: 2
potts_df:
  value: 5
potts_lambda_J:
  value: 3.754492106206564
potts_p_edge:
  value: 0.5593706579230583
potts_p_rescue:
  value: 0.05446797513133778
seed:
  value: 2
seq_length:
  value: 35
