wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 4.9955796994596655
potts_p_edge:
  value: 0.7690995742138627
potts_p_rescue:
  value: 0.09691791044329648
seed:
  value: 1
seq_length:
  value: 15
