wandb_version: 1

mut_rate_int:
  value: 10
potts_df:
  value: 10
potts_lambda_J:
  value: 4.544059331512303
potts_p_edge:
  value: 0.9336938696881898
potts_p_rescue:
  value: 0.00962192291519015
seed:
  value: 1
seq_length:
  value: 60
