wandb_version: 1

mut_rate_int:
  value: 8
potts_df:
  value: 5
potts_lambda_J:
  value: 4.740934525004143
potts_p_edge:
  value: 0.8176644991374211
potts_p_rescue:
  value: 0.24161900424260707
seed:
  value: 2
seq_length:
  value: 25
