wandb_version: 1

mut_rate_int:
  value: 8
potts_df:
  value: 20
potts_lambda_J:
  value: 4.691413431292224
potts_p_edge:
  value: 0.8417918722133795
potts_p_rescue:
  value: 0.018664463943223807
seed:
  value: 1
seq_length:
  value: 60
