wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 10
potts_lambda_J:
  value: 3.330694871810975
potts_p_edge:
  value: 0.7875208219360117
potts_p_rescue:
  value: 0.04708880264650076
seed:
  value: 0
seq_length:
  value: 15
