wandb_version: 1

mut_rate_int:
  value: 4
potts_df:
  value: 2
potts_lambda_J:
  value: 2.8874238587949255
potts_p_edge:
  value: 0.30906793861358894
potts_p_rescue:
  value: 0.1112277648419497
seed:
  value: 2
seq_length:
  value: 25
