wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.544374503751638
potts_p_edge:
  value: 0.8568183846575776
potts_p_rescue:
  value: 0.07891783216692862
seed:
  value: 0
seq_length:
  value: 20
