wandb_version: 1

mut_rate_int:
  value: 10
potts_df:
  value: 5
potts_lambda_J:
  value: 1.150827894401759
potts_p_edge:
  value: 0.6214266556910057
potts_p_rescue:
  value: 0.22789002847751208
seed:
  value: 2
seq_length:
  value: 15
