wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.228384234960952
potts_p_edge:
  value: 0.8123961233877945
potts_p_rescue:
  value: 0.01747246396720774
seed:
  value: 0
seq_length:
  value: 20
