wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.75591693957966
potts_p_edge:
  value: 0.6049026796393309
potts_p_rescue:
  value: 0.002014461330571682
seed:
  value: 2
seq_length:
  value: 80
