wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 3.647128887737913
potts_p_edge:
  value: 0.947798492003418
potts_p_rescue:
  value: 0.10845867071591356
seed:
  value: 1
seq_length:
  value: 20
