wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 3.8783952246789744
potts_p_edge:
  value: 0.6574197758206124
potts_p_rescue:
  value: 0.13017194707722016
seed:
  value: 2
seq_length:
  value: 15
