wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 4.684405093072005
potts_p_edge:
  value: 0.619560503278522
potts_p_rescue:
  value: 0.0639659646968239
seed:
  value: 2
seq_length:
  value: 30
