wandb_version: 1

mut_rate_int:
  value: 6
potts_df:
  value: 5
potts_lambda_J:
  value: 3.1977423549059565
potts_p_edge:
  value: 0.3933090152179866
potts_p_rescue:
  value: 0.17562652820693417
seed:
  value: 1
seq_length:
  value: 20
