wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 3.052617706593385
potts_p_edge:
  value: 0.89459682774428
potts_p_rescue:
  value: 0.1673318602820322
seed:
  value: 1
seq_length:
  value: 15
