wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 4.380142896168309
potts_p_edge:
  value: 0.754315236548681
potts_p_rescue:
  value: 0.12020461339591308
seed:
  value: 2
seq_length:
  value: 15
