wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 2
potts_lambda_J:
  value: 2.763931722490913
potts_p_edge:
  value: 0.5083066587596807
potts_p_rescue:
  value: 0.25008743772329584
seed:
  value: 2
seq_length:
  value: 15
