wandb_version: 1

mut_rate_int:
  value: 10
potts_df:
  value: 5
potts_lambda_J:
  value: 4.07396095853054
potts_p_edge:
  value: 0.4838187498413275
potts_p_rescue:
  value: 0.23194128873997497
seed:
  value: 0
seq_length:
  value: 80
