wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 2
potts_lambda_J:
  value: 4.932432150748426
potts_p_edge:
  value: 0.8714893553113436
potts_p_rescue:
  value: 0.05736432561636101
seed:
  value: 0
seq_length:
  value: 20
