wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.408029059350029
potts_p_edge:
  value: 0.8022188240182735
potts_p_rescue:
  value: 0.05721437287040144
seed:
  value: 2
seq_length:
  value: 15
