wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 2
potts_lambda_J:
  value: 2.216860731318366
potts_p_edge:
  value: 0.9369075201798788
potts_p_rescue:
  value: 0.23160917176475723
seed:
  value: 0
seq_length:
  value: 35
