wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.568668998462282
potts_p_edge:
  value: 0.91334341255424
potts_p_rescue:
  value: 0.032676404899511055
seed:
  value: 2
seq_length:
  value: 100
