wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 10
potts_lambda_J:
  value: 4.595585246525416
potts_p_edge:
  value: 0.8001896528358718
potts_p_rescue:
  value: 0.10072437832560067
seed:
  value: 1
seq_length:
  value: 30
