wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 2.9466827257045125
potts_p_edge:
  value: 0.6802308133743793
potts_p_rescue:
  value: 0.12208362356895372
seed:
  value: 2
seq_length:
  value: 35
