wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.970807872226251
potts_p_edge:
  value: 0.939076992835678
potts_p_rescue:
  value: 0.030768288873196124
seed:
  value: 1
seq_length:
  value: 60
