wandb_version: 1

mut_rate_int:
  value: 10
potts_df:
  value: 2
potts_lambda_J:
  value: 0.941248683468208
potts_p_edge:
  value: 0.6576395286794187
potts_p_rescue:
  value: 0.28301132095697673
seed:
  value: 2
seq_length:
  value: 30
