wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 3.4795362232436204
potts_p_edge:
  value: 0.6998146512706456
potts_p_rescue:
  value: 0.0185335894293177
seed:
  value: 1
seq_length:
  value: 41
