wandb_version: 1

mut_rate_int:
  value: 2
potts_df:
  value: 5
potts_lambda_J:
  value: 0.7138093976615987
potts_p_edge:
  value: 0.33900267837823805
potts_p_rescue:
  value: 0.213598843041093
seed:
  value: 1
seq_length:
  value: 25
