wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 2.59161852273763
potts_p_edge:
  value: 0.90039889923902
potts_p_rescue:
  value: 0.05895050359772985
seed:
  value: 2
seq_length:
  value: 15
