wandb_version: 1

mut_rate_int:
  value: 2
potts_df:
  value: 10
potts_lambda_J:
  value: 4.0661723110728225
potts_p_edge:
  value: 0.7784516216419461
potts_p_rescue:
  value: 0.2881568488161325
seed:
  value: 2
seq_length:
  value: 20
