wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 2.7258779545331753
potts_p_edge:
  value: 0.8217943676026367
potts_p_rescue:
  value: 0.24339996130646
seed:
  value: 2
seq_length:
  value: 15
