wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 3.489073494258564
potts_p_edge:
  value: 0.8874302429509435
potts_p_rescue:
  value: 0.07638641312691316
seed:
  value: 2
seq_length:
  value: 25
