wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.40902594840259
potts_p_edge:
  value: 0.9098147343589588
potts_p_rescue:
  value: 0.09079932169540685
seed:
  value: 0
seq_length:
  value: 80
