wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 3.762529987957307
potts_p_edge:
  value: 0.7110727223804361
potts_p_rescue:
  value: 0.18709520663607096
seed:
  value: 1
seq_length:
  value: 20
