wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 10
potts_lambda_J:
  value: 3.167840802002506
potts_p_edge:
  value: 0.672155364127985
potts_p_rescue:
  value: 0.13601193323538072
seed:
  value: 0
seq_length:
  value: 15
