wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 3.548863363233476
potts_p_edge:
  value: 0.8289550313623524
potts_p_rescue:
  value: 0.12840616514308403
seed:
  value: 1
seq_length:
  value: 15
