wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 2.5392860112662103
potts_p_edge:
  value: 0.8219818793385794
potts_p_rescue:
  value: 0.2064240016295928
seed:
  value: 2
seq_length:
  value: 20
