wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 3.062963482125283
potts_p_edge:
  value: 0.7068955870866019
potts_p_rescue:
  value: 0.119508171877274
seed:
  value: 2
seq_length:
  value: 15
