wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.671010020756588
potts_p_edge:
  value: 0.5498669736943586
potts_p_rescue:
  value: 0.11381168201761288
seed:
  value: 2
seq_length:
  value: 25
