wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.030478212871575
potts_p_edge:
  value: 0.797678852910977
potts_p_rescue:
  value: 6.812953508816832e-05
seed:
  value: 1
seq_length:
  value: 25
