wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.383179549468943
potts_p_edge:
  value: 0.7658934572442024
potts_p_rescue:
  value: 0.0272114173725436
seed:
  value: 0
seq_length:
  value: 60
