wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.859609379441002
potts_p_edge:
  value: 0.8666737777458404
potts_p_rescue:
  value: 0.20247757046088607
seed:
  value: 1
seq_length:
  value: 15
