wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 3.712178767068443
potts_p_edge:
  value: 0.72401527727315
potts_p_rescue:
  value: 0.10593941653045544
seed:
  value: 2
seq_length:
  value: 20
