wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 1.6491927145348786
potts_p_edge:
  value: 0.72499226058041
potts_p_rescue:
  value: 0.0631878739500174
seed:
  value: 2
seq_length:
  value: 41
