wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 4.66285524335309
potts_p_edge:
  value: 0.6377432187710294
potts_p_rescue:
  value: 0.008465164546884717
seed:
  value: 2
seq_length:
  value: 15
