wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.065758241219837
potts_p_edge:
  value: 0.7982971506821434
potts_p_rescue:
  value: 0.1489505254619717
seed:
  value: 0
seq_length:
  value: 25
