wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 4.864879884406673
potts_p_edge:
  value: 0.7897411329942899
potts_p_rescue:
  value: 0.06073700771721935
seed:
  value: 0
seq_length:
  value: 25
