wandb_version: 1

mut_rate_int:
  value: 4
potts_df:
  value: 10
potts_lambda_J:
  value: 2.3960090025223915
potts_p_edge:
  value: 0.8064994847130855
potts_p_rescue:
  value: 0.12497423476507208
seed:
  value: 0
seq_length:
  value: 41
