wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 3.9231021552724106
potts_p_edge:
  value: 0.7427349452508387
potts_p_rescue:
  value: 0.2407149882803589
seed:
  value: 2
seq_length:
  value: 15
