wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 3.212298153034917
potts_p_edge:
  value: 0.90135365524277
potts_p_rescue:
  value: 0.17783067033933964
seed:
  value: 1
seq_length:
  value: 15
