wandb_version: 1

mut_rate_int:
  value: 6
potts_df:
  value: 2
potts_lambda_J:
  value: 2.9166710608286164
potts_p_edge:
  value: 0.7392553195579283
potts_p_rescue:
  value: 0.25981889419549586
seed:
  value: 2
seq_length:
  value: 80
