wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.5039582283141755
potts_p_edge:
  value: 0.6959873484930199
potts_p_rescue:
  value: 0.0535190060695341
seed:
  value: 0
seq_length:
  value: 25
