wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 3.9295462315998817
potts_p_edge:
  value: 0.9092321257781
potts_p_rescue:
  value: 0.10389673775450116
seed:
  value: 2
seq_length:
  value: 25
