wandb_version: 1

mut_rate_int:
  value: 8
potts_df:
  value: 20
potts_lambda_J:
  value: 4.916601128243209
potts_p_edge:
  value: 0.6610876393461502
potts_p_rescue:
  value: 0.18493167897018264
seed:
  value: 0
seq_length:
  value: 15
