wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.04592546322098
potts_p_edge:
  value: 0.6818096023763541
potts_p_rescue:
  value: 0.13753141234531582
seed:
  value: 2
seq_length:
  value: 25
