wandb_version: 1

mut_rate_int:
  value: 6
potts_df:
  value: 5
potts_lambda_J:
  value: 1.9245365213534824
potts_p_edge:
  value: 0.8548779908926665
potts_p_rescue:
  value: 0.1845167466185174
seed:
  value: 0
seq_length:
  value: 100
