wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 10
potts_lambda_J:
  value: 3.488603122344153
potts_p_edge:
  value: 0.8922992766396718
potts_p_rescue:
  value: 0.14873029845674995
seed:
  value: 2
seq_length:
  value: 15
