wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 3.833692793028103
potts_p_edge:
  value: 0.7957170989545379
potts_p_rescue:
  value: 0.09707286254827556
seed:
  value: 2
seq_length:
  value: 20
