wandb_version: 1

mut_rate_int:
  value: 10
potts_df:
  value: 10
potts_lambda_J:
  value: 4.789409898093615
potts_p_edge:
  value: 0.6800116158593638
potts_p_rescue:
  value: 0.0629428171593787
seed:
  value: 1
seq_length:
  value: 30
