wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 3.0735426614317
potts_p_edge:
  value: 0.8276860520044382
potts_p_rescue:
  value: 0.12021771756510612
seed:
  value: 2
seq_length:
  value: 15
