wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 1.6347174054464102
potts_p_edge:
  value: 0.65560586203587
potts_p_rescue:
  value: 0.2109758293596939
seed:
  value: 2
seq_length:
  value: 25
