wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 2
potts_lambda_J:
  value: 4.99040706293143
potts_p_edge:
  value: 0.4916234885290287
potts_p_rescue:
  value: 0.029678497715324936
seed:
  value: 0
seq_length:
  value: 20
