wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.568615600287549
potts_p_edge:
  value: 0.8449167453320408
potts_p_rescue:
  value: 0.15330099649290402
seed:
  value: 0
seq_length:
  value: 30
