wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 10
potts_lambda_J:
  value: 4.597033605745302
potts_p_edge:
  value: 0.6932943176022228
potts_p_rescue:
  value: 0.1308445347119933
seed:
  value: 0
seq_length:
  value: 15
