wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 1.855110806946856
potts_p_edge:
  value: 0.8839347134114801
potts_p_rescue:
  value: 0.01736197016949913
seed:
  value: 2
seq_length:
  value: 80
