wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 3.26889249955196
potts_p_edge:
  value: 0.6778276571130066
potts_p_rescue:
  value: 0.055027477044953386
seed:
  value: 1
seq_length:
  value: 20
