wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 3.37621299608538
potts_p_edge:
  value: 0.7848478710391544
potts_p_rescue:
  value: 0.0724047632875134
seed:
  value: 0
seq_length:
  value: 20
