wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 2
potts_lambda_J:
  value: 4.358193240089458
potts_p_edge:
  value: 0.3267169809257338
potts_p_rescue:
  value: 0.13359219935127503
seed:
  value: 0
seq_length:
  value: 30
