wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.665876176250525
potts_p_edge:
  value: 0.7622266458524856
potts_p_rescue:
  value: 0.12661850414642592
seed:
  value: 2
seq_length:
  value: 20
