wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 4.436587589228758
potts_p_edge:
  value: 0.9063184430428564
potts_p_rescue:
  value: 0.007790034009645407
seed:
  value: 1
seq_length:
  value: 35
