wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 3.2964562509990745
potts_p_edge:
  value: 0.880084827975212
potts_p_rescue:
  value: 0.08887776183018326
seed:
  value: 1
seq_length:
  value: 20
