wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 3.977206548431136
potts_p_edge:
  value: 0.8349901087063074
potts_p_rescue:
  value: 0.03664984666564758
seed:
  value: 1
seq_length:
  value: 25
