wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.263905278768031
potts_p_edge:
  value: 0.7871651937599016
potts_p_rescue:
  value: 0.0964302704590694
seed:
  value: 1
seq_length:
  value: 15
