wandb_version: 1

mut_rate_int:
  value: 10
potts_df:
  value: 2
potts_lambda_J:
  value: 1.5856374223451812
potts_p_edge:
  value: 0.6964628081175293
potts_p_rescue:
  value: 0.14789246243685245
seed:
  value: 2
seq_length:
  value: 60
