wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.782772311494108
potts_p_edge:
  value: 0.8251051415196751
potts_p_rescue:
  value: 0.15379041478935948
seed:
  value: 2
seq_length:
  value: 20
