wandb_version: 1

mut_rate_int:
  value: 2
potts_df:
  value: 2
potts_lambda_J:
  value: 4.4565015613693095
potts_p_edge:
  value: 0.9001744922958106
potts_p_rescue:
  value: 0.0607713436476968
seed:
  value: 0
seq_length:
  value: 35
