wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 3.876547101761955
potts_p_edge:
  value: 0.42424498115923126
potts_p_rescue:
  value: 0.06197694043487531
seed:
  value: 1
seq_length:
  value: 15
