wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.779960840621441
potts_p_edge:
  value: 0.733816804266407
potts_p_rescue:
  value: 0.10994486145350464
seed:
  value: 1
seq_length:
  value: 25
