wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 0.7226977832055486
potts_p_edge:
  value: 0.9423847179694608
potts_p_rescue:
  value: 0.01348397235858385
seed:
  value: 1
seq_length:
  value: 25
