wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 2
potts_lambda_J:
  value: 1.044544690392024
potts_p_edge:
  value: 0.3268589412178398
potts_p_rescue:
  value: 0.26432150570250246
seed:
  value: 0
seq_length:
  value: 41
