wandb_version: 1

mut_rate_int:
  value: 2
potts_df:
  value: 20
potts_lambda_J:
  value: 3.908898207339849
potts_p_edge:
  value: 0.5354094566130807
potts_p_rescue:
  value: 0.24501331948419697
seed:
  value: 2
seq_length:
  value: 41
