wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 2
potts_lambda_J:
  value: 4.147283307663248
potts_p_edge:
  value: 0.9114319028879788
potts_p_rescue:
  value: 0.08163951329437776
seed:
  value: 0
seq_length:
  value: 20
