wandb_version: 1

mut_rate_int:
  value: 8
potts_df:
  value: 20
potts_lambda_J:
  value: 3.632409315880575
potts_p_edge:
  value: 0.7374504352485776
potts_p_rescue:
  value: 0.03300647373819904
seed:
  value: 0
seq_length:
  value: 30
