wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 4.202228139864355
potts_p_edge:
  value: 0.7876510243079687
potts_p_rescue:
  value: 0.12222990552282398
seed:
  value: 1
seq_length:
  value: 20
