wandb_version: 1

mut_rate_int:
  value: 8
potts_df:
  value: 20
potts_lambda_J:
  value: 4.836461591304217
potts_p_edge:
  value: 0.4647127526550463
potts_p_rescue:
  value: 0.104381420901985
seed:
  value: 0
seq_length:
  value: 25
