wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 4.024971526318248
potts_p_edge:
  value: 0.7550797153851952
potts_p_rescue:
  value: 0.13770656179451912
seed:
  value: 1
seq_length:
  value: 30
