wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 10
potts_lambda_J:
  value: 3.624012717046886
potts_p_edge:
  value: 0.8711073945189529
potts_p_rescue:
  value: 0.16523640120272326
seed:
  value: 1
seq_length:
  value: 15
