wandb_version: 1

mut_rate_int:
  value: 8
potts_df:
  value: 20
potts_lambda_J:
  value: 3.459478613584881
potts_p_edge:
  value: 0.6302785087949607
potts_p_rescue:
  value: 0.07147460549228453
seed:
  value: 1
seq_length:
  value: 30
