wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 10
potts_lambda_J:
  value: 3.49669299046836
potts_p_edge:
  value: 0.8475690745101208
potts_p_rescue:
  value: 0.2059498931233917
seed:
  value: 2
seq_length:
  value: 20
