wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 2.924924410176085
potts_p_edge:
  value: 0.8503969508656941
potts_p_rescue:
  value: 0.17968425242181363
seed:
  value: 2
seq_length:
  value: 30
