wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 4.512673981827723
potts_p_edge:
  value: 0.6976172946312611
potts_p_rescue:
  value: 0.01696571025049365
seed:
  value: 0
seq_length:
  value: 15
