wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 3.927906811102967
potts_p_edge:
  value: 0.7396035738515327
potts_p_rescue:
  value: 0.25504504054939736
seed:
  value: 2
seq_length:
  value: 30
