wandb_version: 1

mut_rate_int:
  value: 6
potts_df:
  value: 20
potts_lambda_J:
  value: 2.9697081305483257
potts_p_edge:
  value: 0.9371326758341916
potts_p_rescue:
  value: 0.13995739215071126
seed:
  value: 1
seq_length:
  value: 41
