wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 20
potts_lambda_J:
  value: 3.520714963317915
potts_p_edge:
  value: 0.6531290877639555
potts_p_rescue:
  value: 0.09370022003900638
seed:
  value: 1
seq_length:
  value: 30
