wandb_version: 1

mut_rate_int:
  value: 14
potts_df:
  value: 5
potts_lambda_J:
  value: 4.704139431866792
potts_p_edge:
  value: 0.7610742526040968
potts_p_rescue:
  value: 0.08136780597077187
seed:
  value: 1
seq_length:
  value: 30
