wandb_version: 1

mut_rate_int:
  value: 2
potts_df:
  value: 5
potts_lambda_J:
  value: 4.237612262546249
potts_p_edge:
  value: 0.8869069658711382
potts_p_rescue:
  value: 0.19791490905009224
seed:
  value: 1
seq_length:
  value: 15
