wandb_version: 1

mut_rate_int:
  value: 8
potts_df:
  value: 5
potts_lambda_J:
  value: 1.517022190244317
potts_p_edge:
  value: 0.38644505901404713
potts_p_rescue:
  value: 0.08101770158265388
seed:
  value: 2
seq_length:
  value: 25
